export const compareTwoArrays = (arr1, arr2) => {
    return arr2.every((value) => arr1.includes(value));
};

//prettier-ignore
export const movieList = [
    {
        id: "movie1",
        name: "Rising Arizona",
        releaseYear: "1987",
        runtime: "1h34m",
        summary:"When a childless couple of an ex-con and an ex-cop decide to help themselves to one of another family's quintuplets, their lives become more complicated than they anticipated.",
        director: ["Joel Coen", "Ethan Coen"],
        writers: ["Joel Coen", "Ethan Coen"],
        actors: ["Nicolas Cage","Holly Hunter","Trey Wilson","John Goodman","William Forsythe","Sam McMurray","Frances McDormand",],
        genre: ["Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt0093822/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/raising_arizona",
            poster:"https://m.media-amazon.com/images/M/MV5BOGUwZTEwZTYtZmQ0OS00NmM1LWE2ZTQtNjZiYmE4ZmUxMjk1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg" ,
        }

    },
    {
        id: "movie2",
        name: "Troy",
        releaseYear: "2004",
        runtime: "2h 43m",
        summary:"An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces and chronicles the fates of the men involved.",
        director: ["Wolfgang Petersen"],
        writers: ["Homer", "David Benioff"],
        actors: ["Brad Pitt", "Eric Bana", "Orlando Bloom", "Julian Glover", "Brian Cox", "Nathan Jones", "Adoni Maropis", "Diane Kruger", "Sean Bean", "Garrett Hedlund"],
        genre: ["Drama", "History"],
        links: {
            imdb: "https://www.imdb.com/title/tt0332452/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/troy",
            poster:"https://www.google.com/search?q=troy&rlz=1C1GCEA_enRS982RS982&sxsrf=AOaemvJGluvsC-l10Bj3UVXBr3A5P_HsKw:1638539325849&tbm=isch&source=iu&ictx=1&fir=L467Cuw1gJr5KM%252CMuimAWKOrdxauM%252C%252Fm%252F01vw8k%253B2EcXFHHwnC0jjM%252CerWJWK99oe78fM%252C_%253BQfTCrxDxu-8pRM%252C48HO_ko48qGUpM%252C_%253BQD_gx5jDkh2rJM%252CC5aCWaXdPRsQCM%252C_%253BGfWVY29oJrrERM%252CQbhuRH9LHqJPFM%252C_%253B0TwwHP9O1hfJeM%252CecQ2xOnISafubM%252C_%253B1P6Ga4qM-eMg-M%252C3wtzHnscBIvSgM%252C_%253BxkUmfJ8u_yiBPM%252CeNJzDIZ4rpMiNM%252C_&vet=1&usg=AI4_-kTp2oPEiYYLjSHBZvZlG0X4s59i3w&sa=X&ved=2ahUKEwirp97T4sf0AhX1g_0HHWkeCo8Q_B16BAhgEAE#imgrc=2EcXFHHwnC0jjM" ,
        }
    },
    {
        id: "movie3",
        name: "The Big Lebowski",
        releaseYear: "1998",
        runtime: "1h 57m",
        summary:"Ultimate L.A. slacker Jeff 'The Dude' Lebowski, mistaken for a millionaire of the same name, seeks restitution for a rug ruined by debt collectors, enlisting his bowling buddies for help while trying to find the millionaire's missing wife.",
        director: ["Joel Coen", "Ethan Coen"],
        writers:["Joel Coen", "Ethan Coen"],
        actors: ["Jeff Bridges", "John Goodman", "Steve Buscemi", "Julianne Moor", "David Huddleston", "Philip Seymour Hoffman"],
        genre: ["Comedy", "Crime", "Sport"],
        links: {
            imdb: "https://www.imdb.com/title/tt0118715/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_big_lebowski",
            poster: "https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_.jpg"
        },
    },
    {
        id: "movie4",
        name: "O Brother, Where Art Thou?",
        releaseYear: "2000",
        runtime: "1h 47m",
        summary:"In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.",
        director: ["Joel Coen", "Ethan Coen"],
        writers:["Joel Coen", "Ethan Coen"],
        actors: ["George Clooney", "John Turturro", "Tim Blake Nelson", "John Goodman", "Holly Hunter", "Chris Thomas King", "Charles Durning"],
        genre: ["Adventure", "Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt0190590/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/o_brother_where_art_thou",
            poster: "https://www.google.com/search?q=O+Brother,+Where+Art+Thou%3F&rlz=1C1GCEA_enRS982RS982&sxsrf=AOaemvICgVAf1_jdV9N9e5yNdgDK1Par9Q:1638540261047&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjVmNaR5sf0AhWY57sIHSxdBWgQ_AUoAXoECAEQAw#imgrc=rRDEZnq00gjAyM"
        },
    },
    {
        id: "movie5",
        name: "Call Me by Your Name",
        releaseYear: "2017",
        runtime: "2h 12m",
        summary:"In 1980s Italy, romance blossoms between a seventeen-year-old student and the older man hired as his father's research assistant.",
        director: ["Luca Guadagnino"],
        writers:["James Ivory", "André Aciman"],
        actors: ["Armie Hammer", "Timothée Chalamet", "Michael Stuhlbarg", "Amira Casar", "Eshter Garrel"],
        genre: [],
        links: {
            imdb: "https://www.imdb.com/title/tt5726616/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/call_me_by_your_name",
            poster: "https://m.media-amazon.com/images/M/MV5BNDk3NTEwNjc0MV5BMl5BanBnXkFtZTgwNzYxNTMwMzI@._V1_.jpg"
        },
    },
    {
        id: "movie6",
        name: "SPACE SWEEPERS",
        releaseYear: "2021",
        runtime: "2h 16m",
        summary:"Set in the year 2092 and follows the crew of a space junk collector ship called The Victory. When they discover a humanoid robot named Dorothy that's known to be a weapon of mass destruction, they get involved in a risky business deal.",
        director: ["Sung-hee Jo"],
        writers:["Sung-hee Jo"],
        actors: ["Song Joong-ki", "Kim Tae-ri", "Jin Seon-kyu", "Hae-Jin Yoo", "Richard Armitage"],
        genre: ["Action", "Adventure", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt12838766/?ref_=ttfc_fc_tt",
            rottenTomatoes: "https://www.rottentomatoes.com/m/space_sweepers",
            poster: "https://m.media-amazon.com/images/M/MV5BZTUxN2M3ZWYtMzc1MC00NTc4LWFhZDItMzViZDg2NmFjMzBhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"
        },
    },
    {
        id: "movie7",
        name: "Nomadland",
        releaseYear: "2000",
        runtime: "1h 47m",
        summary:"A woman in her sixties, after losing everything in the Great Recession, embarks on a journey through the American West, living as a van-dwelling modern-day nomad.",
        director: ["Chloé Zhao"],
        writers:["Chloé Zhao", "Jessica Bruder"],
        actors: ["Frances McDormand", "David Strathairn", "Linda May", "Gay DeForest", "Patricia Grier", "Angela Reyes", "Carl R. Hughes", "Douglas G. Soul"],
        genre: ["Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt9770150/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/nomadland",
            poster: "https://m.media-amazon.com/images/M/MV5BMDRiZWUxNmItNDU5Yy00ODNmLTk0M2ItZjQzZTA5OTJkZjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"
        },
    },
    {
        id: "movie8",
        name: "Akira",
        releaseYear: "1988",
        runtime: "2h 4m",
        summary:"A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by a teenager, his gang of biker friends and a group of psychics.",
        director: ["Katsuhiro Ôtomo"],
        writers:["Katsuhiro Ôtomo", "Izô Hashimoto"],
        actors: ["Mitsuo Iwata", "Nozomu Sasaki", "Mami Koyama", "Tesshô Genda"],
        genre: ["Animation", "Action", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt0094625/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/akira",
            poster: "https://m.media-amazon.com/images/M/MV5BM2ZiZTk1ODgtMTZkNS00NTYxLWIxZTUtNWExZGYwZTRjODViXkEyXkFqcGdeQXVyMTE2MzA3MDM@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie9",
        name: "The Bourne Identity",
        releaseYear: "2002",
        runtime: "1h 59m",
        summary:"A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and attempting to regain his memory.",
        director: ["Doug Liman"],
        writers:["Tony Gilroy", "W. Blake Heron", "Robert Ludlum"],
        actors: ["Matt Damon", "Franka Potente", "Chris Cooper", "Clive Owen", "Brian Cox", "Julia Stiles"],
        genre: ["Action", "Mystery", "Thriller"],
        links: {
            imdb: "",
            rottenTomatoes: "https://www.rottentomatoes.com/m/bourne_identity",
            poster: "https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg"
        },
    },
    {
        id: "movie10",
        name: "Monster Hunter",
        releaseYear: "2020",
        runtime: "1h 43m",
        summary:"When Cpt. Artemis and her loyal soldiers are transported to a new world, they engage in a desperate battle for survival against enormous enemies with incredible powers. Feature film based on the video game by Capcom.",
        director: ["Paul W.S. Anderson"],
        writers:["Paul W.S Anderson", "kaname Fujioka"],
        actors: ["Milla Jovovich", "Tony Jaa", "Ron Perlman", "T.I", "Diego Boneta", "Meagan Good", "Lathalos"],
        genre: ["Action", "Adventure", "Fantasy"],
        links: {
            imdb: "https://www.imdb.com/title/tt6475714/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/monster_hunter",
            poster: "https://m.media-amazon.com/images/M/MV5BOGU3NTFmNjYtODc3Ny00MWEzLWI3M2ItZjE3NDgwMTI0MzkzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg"
        },
    },
    {
        id: "movie11",
        name: "The Bourne Supremacy",
        releaseYear: "2004",
        runtime: "1h 48m",
        summary:"When Jason Bourne is framed for a CIA operation gone awry, he is forced to resume his former life as a trained assassin to survive.",
        director: ["Paul GreenGrass"],
        writers:["Robert Ludlum", "Tony Gilroy"],
        actors: ["Matt Damon", "Franka Potente", "Joan Allen", "Brian Cox", "Julia Stiles", "Karl Urban"],
        genre: ["Action", "Mystery", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt0372183/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/bourne_supremacy",
            poster: "https://m.media-amazon.com/images/M/MV5BYTIyMDFmMmItMWQzYy00MjBiLTg2M2UtM2JiNDRhOWE4NjBhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg"
        },
    },
    {
        id: "movie12",
        name: "Wolfwalkers",
        releaseYear: "2020",
        runtime: "1h 43m",
        summary:"A young apprentice hunter and her father journey to Ireland to help wipe out the last wolf pack. But everything changes when she befriends a free-spirited girl from a mysterious tribe rumored to transform into wolves by night.",
        director: ["Tomm Moore", "Ross Stewart"],
        writers:["Will Collins", "Tomm Moore", "Ross Stewart"],
        actors: ["Honor Kneafsey", "Eva Whittaker", "Sean Bean", "Simon McBurney", "Tommy Tiernan", "Maria Doyle Kennedy"],
        genre: ["Animation", "Adventure", "Family"],
        links: {
            imdb: "https://www.imdb.com/title/tt5198068/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/wolfwalkers",
            poster: "https://m.media-amazon.com/images/M/MV5BNTA4MWQ4NGUtOGQ0MS00M2QyLWE5MDItZWM2YzA0ZDgxZTA2XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg"
        },
    },
    {
        id: "movie13",
        name: "Justice League",
        releaseYear: "2017",
        runtime: "2h",
        summary:"Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.",
        director: ["Zack Snyder"],
        writers:["Jerry Siegel", "joe Shuster", "Chris Terrio"],
        actors: ["ben Affleck", "Gal Gadot", "Jason Momoa", "Ezra Miller", "Henry Cavill", "Amy Adams", "Ray Fisher", "Jeremy Irons", "Diane Lane", "Connie Nielsen", "J.K Simmons"],
        genre: ["Action", "Adventure", "Fantasy", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt0974015/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/zack_snyders_justice_league",
            poster: "https://images-na.ssl-images-amazon.com/images/I/81KX513BQxL.jpg"
        },
    },
    {
        id: "movie14",
        name: "Moonlight",
        releaseYear: "2016",
        runtime: "1h 51m",
        summary: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood",
        director: ["Barry Jenkins"],
        writers:["Barry Jenkins", "Tarell Alvin McCraney"],
        actors: ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes", "Alex R. Hibbert", "Shariff Earp", "Duan Sanderson", "Janelle Monáe", "Jaden Piner"],
        genre: ["Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt4975722/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/moonlight_2016",
            poster: "https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie15",
        name: "Avengers: Age of Ultron",
        releaseYear: "2015",
        runtime: "2h 21m",
        summary:"When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
        director: ["Joss Whedon"],
        writers:["Joss Whedon", "Jack Kirby"],
        actors: ["Robert Downey Jr", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson", "Jeremy Renner", "James Spader", "Samuel L. Jackson", "Don Cheadle", "Aaron Tylor-Johnson", "Elizabeth Olsen", "Paul Bettany", "Anthony Mackie"],
        genre: ["Action", "Adventure", "Sci-Fi", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt2395427/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/avengers_age_of_ultron",
            poster: "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie16",
        name: "Promising Young Woman",
        releaseYear: "2020",
        runtime: "1h 53m",
        summary:"A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.",
        director: ["Emerald Fennell"],
        writers:["Emerald Fennell"],
        actors: ["Carey Mulligan", "Bo Burnham", "Alison Brie", "Clancy Brown", "Adam Brody", "Ray Nicholson", "Sam Richardson"],
        genre: ["Crime", "Drama", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt9620292/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/promising_young_woman",
            poster: "https://m.media-amazon.com/images/M/MV5BOTgzMzE4MGItZDgxYS00ZGEwLWE3YTctZWY3ZDAyMTk0ZGU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie17",
        name: "Gladiator",
        releaseYear: "2000",
        runtime: "2h 35m",
        summary:"A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        director: ["Ridley Scott"],
        writers:["David Franzoni", "John Logan", "William Nicholson"],
        actors: ["Russell Crowe", "Joaquin Phoenix", "connie Nielsen", "Oliver Reed", "Richard Harris", "Derek Jacobi", "Djimon Hounsou", "David Schofield"],
        genre: ["Action", "Adventure", "Drama", "History"],
        links: {
            imdb: "https://www.imdb.com/title/tt0172495/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/gladiator",
            poster: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg"
        },
    },
    {
        id: "movie18",
        name: "Sound of Metal",
        releaseYear: "2020",
        runtime: "2h",
        summary:"A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
        director: ["Darius Marder"],
        writers:["Darius Marder", "Abraham Marder", "Derek Cianfrance"],
        actors: ["Riz Ahmed", "Olivia Cooke", "Paul Raci", "Lauren Ridloff", "Mathieu Amalric", "Chelsea Lee"],
        genre: ["Drama", "Music"],
        links: {
            imdb: "https://www.imdb.com/title/tt5363618/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/sound_of_metal",
            poster: "https://m.media-amazon.com/images/M/MV5BNjcyYjg0M2ItMzMyZS00NmM1LTlhZDMtN2MxN2RhNWY4YTkwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie19",
        name: "Godzilla vs Kong",
        releaseYear: "2021",
        runtime: "1h 53m",
        summary:"The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.",
        director: ["Adam Wingard"],
        writers:["Terry Rossio", "Michael Dougherty", "Zach Shields"],
        actors: ["Alexander Skarsgård", "Millie Bobby Brown", "Rebecca Hall", "Brian Tyree Henry", "Shun Oguri", "Eiza Gonzalez", "Julian Dennison", "Lance Reddick"],
        genre: ["Action", "Sci-Fi", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt5034838/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/godzilla_vs_kong",
            poster: "https://m.media-amazon.com/images/M/MV5BMzk2ZmYxNTUtODlhMi00NzE2LTkwMTctYjg0ODQ1ZjkyNzJmXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg"
        },
    },
    {
        id: "movie20",
        name: "Captain America: Civil War",
        releaseYear: "2016",
        runtime: "2h 27m",
        summary:"Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
        director: ["Anthony Russo", "Joe Russo"],
        writers:["Christopher Markus", "Stephen McFeely", "Joe Simon"],
        actors: ["Robert Downey Jr", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson", "Jeremy Renner", "Sebastian Stan", "Chadwick Boseman", "Don Cheadle", "Elizabeth Olsen", "Paul Bettany", "Anthony Mackie", "Tom Holland", "Daniel Brühl"],
        genre: ["Action", "Adventure", "Sci-Fi", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt3498820/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/captain_america_civil_war",
            poster: "https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_.jpg"
        },
    },
    {
        id: "movie21",
        name: "Another Round",
        releaseYear: "2020",
        runtime: "1h 57m",
        summary:"Four high school teachers consume alcohol on a daily basis to see how it affects their social and professional lives.",
        director: ["Thomas Vinterberg"],
        writers:["Thomas Vinterberg", "Tobias Lindholm"],
        actors: ["Mads Mikkelsen", "Thomas Bo Larsen", "Magnus Millang", "Lars Ranthe"],
        genre: ["Comedy", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt10288566/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/another_round",
            poster: "https://m.media-amazon.com/images/M/MV5BOTNjM2Y2ZjgtMDc5NS00MDQ1LTgyNGYtYzYwMTAyNWQwYTMyXkEyXkFqcGdeQXVyMjE4NzUxNDA@._V1_.jpg"
        },
    },
    {
        id: "movie22",
        name: "Minari",
        releaseYear: "2020",
        runtime: "1h 55m",
        summary:"A Korean family starts a farm in 1980s Arkansas.",
        director: ["Lee Isaac Chung"],
        writers:["Lee Isaac Chung"],
        actors: ["Steven Yeun", "Yeri Han", "Alan S. Kim", "Noel Cho"],
        genre: ["Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt10633456/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/minari",
            poster: "https://images-na.ssl-images-amazon.com/images/I/91Jf7iEaGnL._RI_.jpg"
        },
    },
    {
        id: "movie23",
        name: "Galaxy Quest",
        releaseYear: "1999",
        runtime: "1h 42m",
        summary:"The alumni cast of a space opera television series have to play their roles as the real thing when an alien race needs their help. However, they also have to defend both Earth and the alien race from a reptilian warlord.",
        director: ["Dean Parisot"],
        writers:["David Howard", "Robert Gordon"],
        actors: ["Tim Allen", "Sigourney Weaver", "Alan Rickman", "Tony Shalhoub", "Sam rockwell"],
        genre: ["Adventure", "Comedy", "Sci-Fi"],
        links: {
            imdb: "https://www.imdb.com/title/tt0177789/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/galaxy_quest",
            poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRSu9zspfkoUELt724TQ1806fuMfdEzwkW8L74WWue47OOa5fTU"
        },
    },
    {
        id: "movie24",
        name: "Big Trouble in Little China",
        releaseYear: "1986",
        runtime: "1h 39m",
        summary:"A rough-and-tumble trucker and his side kick face off with an ancient sorcerer in a supernatural battle beneath Chinatown.",
        director: ["John Carpenter"],
        writers:["Gary Coldman", "David Z. Weinstein", "W.D Richter"],
        actors: ["Kurt Russell", "Kim Cattrall", "Dennis Dun", "James Hong", "Victor Wong", "Kate Burton", "Donald Li", "Carter Wong"],
        genre: ["Action", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt0090728/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/big_trouble_in_little_china",
            poster: "https://m.media-amazon.com/images/M/MV5BNzlhYjEzOGItN2MwNS00ODRiLWE5OTItYThiNmJlMTdmMzgxXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg"
        },
    },
    {
        id: "movie25",
        name: "Mortal Kombat",
        releaseYear: "2021",
        runtime: "1h 50m",
        summary:"MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.",
        director: ["Simon McQuoid"],
        writers:["Greg Russo", "Dave Callaham", "Oren Uziel"],
        actors: ["Lewis Tan", "Jessica McNamee", "Josh Lawson", "Joe Taslim", "Mechcad Brooks", "Matilda Kimber", "Laura Brent", "Tadanobu Asano"],
        genre: ["Action", "Adventure", "Fantasy"],
        links: {
            imdb: "https://www.imdb.com/title/tt0293429/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/mortal_kombat_2021",
            poster: "https://wallpapercave.com/wp/wp8592034.png"
        },
    },
    {
        id: "movie26",
        name: "Being John Malkovich",
        releaseYear: "1999",
        runtime: "1h 53m",
        summary:"A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich.",
        director: ["Spike Jonze"],
        writers:["Charlie Kaufman"],
        actors: ["John Cusack", "Cameron Diaz", "Catherine Keener", "John Malkovich" ],
        genre: ["Comedy", "Drama", "Fantasy"],
        links: {
            imdb: "https://www.imdb.com/title/tt0120601/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/being_john_malkovich",
            poster: "https://flxt.tmsimg.com/assets/p23903_p_v10_aa.jpg"
        },
    },
    {
        id: "movie27",
        name: "Halloween",
        releaseYear: "1978",
        runtime: "1h 31m",
        summary:"Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.",
        director: ["John Carpenter"],
        writers:["John Carpenter", "Debra Hill"],
        actors: ["Donald Pleasence", "Jamie Lee Curtis", "Tony Moran", "Nancy Kyes"],
        genre: ["Horror", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt0077651/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/1009113-halloween",
            poster: "https://m.media-amazon.com/images/M/MV5BZTA0YmE2YWUtYjdjMS00YTcxLTkyZmYtZDY2NGEyZTBkZWJhXkEyXkFqcGdeQXVyMjgyNDU4MjE@._V1_.jpg"
        },
    },
    {
        id: "movie28",
        name: "The Mitchells vs the Machines",
        releaseYear: "2021",
        runtime: "1h 53m",
        summary:"A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
        director: ["Michael Rianda", "Jeff Rowe"],
        writers:["Michael Rianda", "Jeff Rowe", "Alex Hirsch"],
        actors: ["Abbi jacobson", "Danny McBride", "Maya Rudolph", "Michael Rianda", "Eric André", "Olivia Colman", "Fred Armisen"],
        genre: ["Animation", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt7979580/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_mitchells_vs_the_machines",
            poster: "https://m.media-amazon.com/images/M/MV5BMjdkZjNjNDItYzc4MC00NTkxLTk1MWEtY2UyZjY5MjUwNDNkXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_.jpg"
        },
    },
    {
        id: "movie29",
        name: "Assault on Precinct 13",
        releaseYear: "1976",
        runtime: "1h 31m",
        summary:"An unlikely partnership between a Highway Patrol Officer, two criminals and a station secretary is formed to defend a defunct Los Angeles precinct office against a siege by a bloodthirsty street gang.",
        director: ["John Carpenter"],
        writers:["John Carpenter"],
        actors: ["Austin Stoker", "Darwin Joston", "Laurie Zimmer", "Martin West", "Tony Burton",],
        genre: ["Action", "Crime", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt0074156/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/assault_on_precinct_13",
            poster: "https://m.media-amazon.com/images/M/MV5BZTQzMTA2ZjItMDA2Mi00YTNjLWFkOTktYTk3Y2JhZTdiYzU5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg"
        },
    },
    {
        id: "movie30",
        name: "The Thing",
        releaseYear: "1982",
        runtime: "1h 49m",
        summary:"A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
        director: ["John Carpenter"],
        writers:["Bill Lancaster", "John W. Campbell Jr."],
        actors: ["Kurt Russell", "Wilford Brimley", "Keith David", "Richard Masur", "T.K Carter", "David Clennon"],
        genre: ["Horror", "Mystery", "Sci-Fi"],
        links: {
            imdb: "https://www.imdb.com/title/tt0084787/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/1021244-thing",
            poster: "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie31",
        name: "Paddington",
        releaseYear: "2014",
        runtime: "1h 35m",
        summary:"A young Peruvian bear travels to London in search of a home. Finding himself lost and alone at Paddington Station, he meets the kindly Brown family, who offer him a temporary haven.",
        director: ["Paul King"],
        writers:["Paul King", "Hamish McColl", "Micheal Bond"],
        actors: ["Hugh Bonneville", "Sally Hawkins", "Julie Walters", "Jim Broadbent", "Tim Downie", "Madeleine Worrall", "Lottie Steer", "Madeleine Harris", "Ben Whishaw", "Samule Joslin"],
        genre: ["Animation", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt1109624/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/paddington_2014",
            poster: "https://m.media-amazon.com/images/I/81PjZQdZJbL._SL1500_.jpg"
        },
    },
    {
        id: "movie32",
        name: "Paddington 2",
        releaseYear: "2017",
        runtime: "1h 43m",
        summary:"Paddington, now happily settled with the Brown family and a popular member of the local community, picks up a series of odd jobs to buy the perfect present for his Aunt Lucy's 100th birthday, only for the gift to be stolen.",
        director: ["Paul King"],
        writers:["Paul King", "Simon Farnaby", "Micheal Bond"],
        actors: ["Ben Whishaw", "Hugh Grant", "Hugh Bonneville", "Sally Hawkins", "Micheal Gambon", "Imelda Staunton", "Madeleine Harris", "Samuel Joslin" ],
        genre: ["Animation", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt4468740/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/paddington_2",
            poster: "https://m.media-amazon.com/images/M/MV5BMmYwNWZlNzEtNjE4Zi00NzQ4LWI2YmUtOWZhNzZhZDYyNmVmXkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie33",
        name: "Escape from L.A.",
        releaseYear: "1996",
        runtime: "1h 41m",
        summary:"Snake Plissken is once again called in by the United States government to recover a potential doomsday device from Los Angeles, now an autonomous island where undesirables are deported.",
        director: ["John Carpenter"],
        writers:["John Carpenter", "Nick Castle", "Debra Hill"],
        actors: ["Kurt Russell", "Steve Buscemi", "Stacy Keach", "A.J. Langer", "Georges Corraface", "Michelle Forbes", "Pam Grier", "Bruce Campbell"],
        genre: ["Action", "Adventure", "Sci-Fi"],
        links: {
            imdb: "https://www.imdb.com/title/tt0116225/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/escape_from_la",
            poster: "https://m.media-amazon.com/images/M/MV5BOWUzNTRmNTQtNWMwZS00MTg4LThhMDUtYmQ5OGQ5MmNmYzNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg"
        },
    },
    {
        id: "movie34",
        name: "The Old Man & the Gun",
        releaseYear: "2018",
        runtime: "1h 33m",
        summary:"Based on the true story of Forrest Tucker and his audacious escape from San Quentin at the age of 70 to an unprecedented string of heists that confounded authorities and enchanted the public.",
        director: ["David Lowery"],
        writers:["David Lowery", "David Grann"],
        actors: ["Robert Redford", "Casey Affleck", "Sissy Spacek", "Danny Glover", "Tom Waits", "Tika Sumpter"],
        genre: ["Biography", "Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt2837574/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_old_man_and_the_gun",
            poster: "https://m.media-amazon.com/images/M/MV5BOTk3NjU5MjIxM15BMl5BanBnXkFtZTgwNjU0OTU2NTM@._V1_.jpg"
        },
    },
    
    {
        id: "movie35",
        name: "Luca",
        releaseYear: "2021",
        runtime: "1h 35m",
        summary:"On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.",
        director: ["Enrico Casarosa"],
        writers:["enrico Casarosa", "Jesse Andrews", "Simon Stephenson"],
        actors: ["Jacob Tremblay", "Jack Dylan Grazer", "Emma Berman", "Saverio Raimondo", "Maya Rudolph", "Marco Barricelli", "Jim Gaffigan"],
        genre: ["Animation", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt12801262/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/luca_2021",
            poster: "https://m.media-amazon.com/images/M/MV5BZTQyNTU0MDktYTFkYi00ZjNhLWE2ODctMzBkM2U1ZTk3YTMzXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie36",
        name: "21 Jump Street",
        releaseYear: "2012",
        runtime: "1h 49m",
        summary:"A pair of underachieving cops are sent back to a local high school to blend in and bring down a synthetic drug ring.",
        director: ["Phill Lord", "Christopher Miller"],
        writers:["Micheal Bacall", "Jonah Hill", "Patrick Hasburgh"],
        actors: ["Jonah Hill", "Channing Tatum", "Ice Cube", "Brie Larson", "Dave Franco", "Rob Riggle", "DeRay Davis", "Dax Flame", "Chris Parnell", "Ellie Kemper", "Jake Johnson", "Nick Offerman"],
        genre: ["Action", "Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt1232829/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/21_jump_street_2011",
            poster: "https://m.media-amazon.com/images/M/MV5BNTZjNzRjMTMtZDMzNy00Y2ZjLTg0OTAtZjVhNzYyZmJjOTljXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
        },
    },
    {
        id: "movie37",
        name: "22 Jump Street",
        releaseYear: "2014",
        runtime: "1h 52m",
        summary:"After making their way through high school (twice), big changes are in store for officers Schmidt and Jenko when they go deep undercover at a local college.",
        director: ["Phill Lord", "Christopher Miller"],
        writers:["Micheal Bacall", "Oren Uziel", "Rodney Rothman"],
        actors: ["Jonah Hill", "Channing Tatum", "Ice Cube", "Nick Offerman", "Peter Stormare", "Wyatt Russell", "Amber Stevens West"],
        genre: ["Action", "Comedy", "Crime"],
        links: {
            imdb: "https://www.imdb.com/title/tt2294449/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/22_jump_street",
            poster: "https://m.media-amazon.com/images/M/MV5BMTcwNzAxMDU1M15BMl5BanBnXkFtZTgwNDE2NTU1MTE@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie38",
        name: "Black Widow",
        releaseYear: "2021",
        runtime: "2h 14m",
        summary:"Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
        director: ["Cate Shortland"],
        writers:["Eric Pearson", "Jac Schaeffer", "Ned Benson"],
        actors: ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz", "Ray Winstone", "Ever Anderson", "Violet McGraw", "O-T Fagbenle", "William Hurt", "Olga Kurylenko"],
        genre: ["Action", "Adventure", "Sci-Fi"],
        links: {
            imdb: "https://www.imdb.com/title/tt3480822/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/black_widow_2021",
            poster: "https://m.media-amazon.com/images/M/MV5BNjRmNDI5MjMtMmFhZi00YzcwLWI4ZGItMGI2MjI0N2Q3YmIwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"
        },
    },
    {
        id: "movie39",
        name: "Hereditary",
        releaseYear: "2018",
        runtime: "2h 7m",
        summary:"A grieving family is haunted by tragic and disturbing occurrences.",
        director: ["Ari Aster"],
        writers:["Ari Aster"],
        actors: ["Toni Collette", "Milly Shapiro", "Gabriel Byrne", "Alex Wolff", "Ann Dowd"],
        genre: ["Drama", "Horror", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt7784604/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/hereditary",
            poster: "https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_.jpg"
        },
    },
    {
        id: "movie40",
        name: "Midsommar",
        releaseYear: "2019",
        runtime: "2h 28m",
        summary:"A couple travels to Eastern Europe to visit a rural hometown's fabled Swedish mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.",
        director: ["ari Aster"],
        writers:["Ari Aster"],
        actors: ["Florence Pugh", "Jack Reynor", "Vilhelm Blomgren", "William Jackson Harper", "Will Poulter", "Ellora Torchia", "Archie Madekwe", "Henrik Norlen"],
        genre: ["Drama", "Horror", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt8772262/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/midsommar",
            poster: "https://m.media-amazon.com/images/M/MV5BMDZjZWE0ZjktZjBlOS00YmFiLWFlYjctY2IwZmUxMzQyZjUyXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg"
        },
    },
    {
        id: "movie41",
        name: "Master and Commander: The Far Side of the World",
        releaseYear: "2003",
        runtime: "2h 18m",
        summary:"During the Napoleonic Wars, a brash British captain pushes his ship and crew to their limits in pursuit of a formidable French war vessel around South America.",
        director: ["Peter Weir"],
        writers:["Patrick O'Brian", "Peter Weir", "John Collee"],
        actors: ["Russell Crowe", "Paul Bettany", "Billy Boyd", "James D'Arcy", "Edward Woodall", "Chris Larkin"],
        genre: ["Action", "Adventure", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt0311113/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/master_and_commander_the_far_side_of_the_world",
            poster: "https://m.media-amazon.com/images/M/MV5BMjA5NjYyMDM5NV5BMl5BanBnXkFtZTYwOTU5MDY2._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie42",
        name: "It",
        releaseYear: "2017",
        runtime: "2h 15m",
        summary:"In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.",
        director: ["Andy Muschietti"],
        writers:["Chase Palmer", "Cary Joji Fukunaga", "Dauberman"],
        actors: ["Bill Skarsgård", "Jaedan Martell", "Finn Wolfhard", "Sophia Lillis", "Jeremy Ray Taylor", "Chosen Jacobs", "jack Dylan Grazer", "Wyatt Oleff"],
        genre: ["Horror"],
        links: {
            imdb: "https://www.imdb.com/title/tt1396484/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/it_2017",
            poster: "https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_.jpg"
        },
    },
    {
        id: "movie43",
        name: "Eighth Grade",
        releaseYear: "2018",
        runtime: "1h 33m",
        summary:"An introverted teenage girl tries to survive the last week of her disastrous eighth grade year before leaving to start high school.",
        director: ["Bo Burnham"],
        writers:["Bo Burnham"],
        actors: ["Elsie Fisher", "Josh Hamilton", "Emily Robinson", "Jake Ryan", "Daniel Zolghadri", "Fred Hechinger"],
        genre: ["Comedy", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt7014006/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/eighth_grade",
            poster: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuXj6kJxHy5kYjKkXjqsUKjQ5YtuJ1x4ymW4cJ5FPZGOAVYPW3"
        },
    },
    {
        id: "movie44",
        name: "Ma Rainey's Black Bottom",
        releaseYear: "2020",
        runtime: "1h 34m",
        summary:"Tensions rise when trailblazing blues singer Ma Rainey and her band gather at a recording studio in Chicago in 1927.",
        director: ["George C. Wolfe"],
        writers:["Ruben Santiago-Hudson", "August Wilson"],
        actors: ["Viola Davis", "Chadwick Boseman", "Glynn Turman", "Colman Domingo", "Michael Potts", "Jeremy Shamos", "Jonny Coyne", "Taylour Paige", "Dusan Brown", "Joshua Harto"],
        genre: ["Drama", "Music"],
        links: {
            imdb: "https://www.imdb.com/title/tt10514222/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/ma_raineys_black_bottom",
            poster: "https://m.media-amazon.com/images/M/MV5BNTBlZGY1OTAtN2RjMC00ZThiLWFiZmUtN2VkOGMxNmMyYjQwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg"
        },
    },
    {
        id: "movie45",
        name: "Lost in Translation",
        releaseYear: "2003",
        runtime: "1h 42m",
        summary:"A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.",
        director: ["Sofia Coppola"],
        writers:["Sofia Coppola"],
        actors: ["Bill Murray", "Scarlett Johansson", "Giovanni Ribisi", "Anna Faris" ],
        genre: ["Comedy", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt0335266/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/lost_in_translation",
            poster: "https://cdn.shopify.com/s/files/1/1057/4964/products/Lost-In-Translation-Vintage-Movie-Poster-Original-1-Sheet-27x41_5fa2337c-80f6-490d-9aee-68f218ef1349_1934x.jpg?v=1632603628"
        },
    },
    {
        id: "movie46",
        name: "Wrath of Man",
        releaseYear: "2021",
        runtime: "1h 59m",
        summary:"The plot follows H, a cold and mysterious character working at a cash truck company responsible for moving hundreds of millions of dollars around Los Angeles each week",
        director: ["Guy Ritchie"],
        writers:["Nicolas Bounkhrief", "Éric Besnard", "Guy Ritchie"],
        actors: ["Jason Statham", "Holt McCallany", "Josh Hartnett", "Rocci Williams", "Jeffrey Donovan", "Scott Eeastwood", "Andy Garcia", "Deobia Oparei"],
        genre: ["Action", "Crime", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt11083552/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/wrath_of_man",
            poster: "https://m.media-amazon.com/images/M/MV5BYTA3MTdiOGMtY2EwNC00OTljLTg1YWItNmNkNDNlOThkOTFmXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg"
        },
    },
    {
        id: "movie47",
        name: "Zack Snyder's Justice League",
        releaseYear: "2017",
        runtime: "2h",
        summary:"Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
        director: ["Zack Snyder"],
        writers:["Jerry Siegel", "Joe Shuster", "Chris Terrio"],
        actors: ["ben Affleck", "Gal Gadot", "Jason Momoa", "Ezra Miller", "Henry Cavill", "Amy Adams", "Ray Fisher", "Jeremy Irons", "Diane Lane", "Connie Nielsen", "J.K Simmons"],
        genre: ["Action", "Adventure", "Fantasy", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt12361974/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/zack_snyders_justice_league",
            poster: "https://m.media-amazon.com/images/M/MV5BYjI3NDg0ZTEtMDEwYS00YWMyLThjYjktMTNlM2NmYjc1OGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg"
        },
    },
    {
        id: "movie48",
        name: "The Suicide Squad",
        releaseYear: "2021",
        runtime: "2h 12m",
        summary:"Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        director: ["James Gunn"],
        writers:["James Gunn"],
        actors: ["Margot Robbie", "Idris Elba", "John Cena", "Joel kinnaman", "Michael Rooker", "Viola Davis", "Nathan Fillion", "Jai Courtney", "Pete Davidson", "Daniela Melchoir", "Sylvester Stallone", "Peter Capaldi", ""],
        genre: ["Action", "Adventure", "Comedy", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt6334354/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_suicide_squad",
            poster: "https://m.media-amazon.com/images/M/MV5BNGM3YzdlOWYtNjViZS00MTE2LWE1MWUtZmE2ZTcxZjcyMmU3XkEyXkFqcGdeQXVyODEyMTI1MjA@._V1_.jpg"
        },
    },
    {
        id: "movie49",
        name: "2001: A Space Odyssey",
        releaseYear: "1968",
        runtime: "2h 29m",
        summary:"The Monoliths push humanity to reach for the stars; after their discovery in Africa generations ago, the mysterious objects lead mankind on an awesome journey to Jupiter, with the help of H.A.L. 9000: the world's greatest supercomputer.",
        director: ["Stanley Kubrick"],
        writers:["Stanley Kubrick", "Arthur C. Clarke"],
        actors: ["Keir Dullea", "Gary Lockwood", "William Sylvester", "Daniel Richter", "Leonard Rossiter", "Margaret Tyzack", "Robert Beatty", "Douglas Rain"],
        genre: ["Adventure", "Sci-Fi"],
        links: {
            imdb: "https://www.imdb.com/title/tt0062622/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/2001_a_space_odyssey",
            poster: "https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg"
        },
    },
    {
        id: "movie50",
        name: "The Green Knight",
        releaseYear: "2021",
        runtime: "2h 10m",
        summary:"A fantasy retelling of the medieval story of Sir Gawain and the Green Knight.",
        director: ["David Lowery"],
        writers:["David Lowery"],
        actors: ["Dev Patel", "Alicia Vikander", "Joel Edgerton", "Sarita Choudhury", "Sean Harris", "Kate Dickie", "Ralph Ineson", "Anaïs Rizzo"],
        genre: ["Adventure", "Drama", "Fantasy"],
        links: {
            imdb: "https://www.imdb.com/title/tt9243804/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_green_knight",
            poster: "https://m.media-amazon.com/images/M/MV5BMjMxNTdiNWMtOWY0My00MjM4LTkwNzMtOGI0YThhN2Q4M2I4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"
        },
    },
    {
        id: "movie51",
        name: "Lion",
        releaseYear: "2016",
        runtime: "1h 58m",
        summary:"A five-year-old Indian boy is adopted by an Australian couple after getting lost hundreds of kilometers from home. 25 years later, he sets out to find his lost family.",
        director: ["Garth Davis"],
        writers:["Saroo Brierley", "Luke Davies"],
        actors: ["Dev Patel", "Nicole Kidman", "Rooney Mara", "Sunny Pawar", "Abhishek Bharate", "Priyanka Bose", "David Wenham", "Rita Boy"],
        genre: ["Biography", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt3741834/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/lion_2016",
            poster: "https://adoptionsupport.org/wp-content/uploads/2017/01/Lion-movie-image.png"
        },
    },
    {
        id: "movie52",
        name: "The Girl with the Dragon Tattoo",
        releaseYear: "2011",
        runtime: "2h 38m",
        summary:"Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years by Lisbeth Salander, a young computer hacker.",
        director: ["David Fincher"],
        writers:["Steven Zaillian", "Stieg Larsson"],
        actors: ["Daniel Craig", "Rooney Mara", "Christopher Plummer", "Stellan Skarsgård", "Steven Berkoff", "Robin Wright",  ],
        genre: ["Crime", "Drama", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt1568346/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/the_girl_with_the_dragon_tattoo",
            poster: "https://m.media-amazon.com/images/M/MV5BMTczNDk4NTQ0OV5BMl5BanBnXkFtZTcwNDAxMDgxNw@@._V1_.jpg"
        },
    },
    {
        id: "movie53",
        name: "The Shining",
        releaseYear: "1980",
        runtime: "2h 26m",
        summary:"A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
        director: ["Stanley Kubrick"],
        writers:["Stephen King", "Stanley Kubrick", "Diane Johnson"],
        actors: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers", "Barry Nelson", "Philip Stone", "Joe Turkel", "Anne Jackson"],
        genre: ["Drama", "Horror"],
        links: {
            imdb: "https://www.imdb.com/title/tt0081505/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/shining",
            poster: "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg"
        },
    },
    {
        id: "movie54",
        name: "Barry Lyndon",
        releaseYear: "1975",
        runtime: "3h 5m",
        summary:"An Irish rogue wins the heart of a rich widow and assumes her dead husband's aristocratic position in 18th-century England.",
        director: ["Stanley Kubrick"],
        writers:["Stanley Kubrick", "William Makepeace Thackeray"],
        actors: ["Ryan O'Neil", "Marisa Berenson", "Patrick Magee", "Hardy Krüger", "Steven Berkoff", "Gay Hamilton", "Marie Kean", "Diana Körner"],
        genre: ["Adventure", "Drama", "History"],
        links: {
            imdb: "https://www.imdb.com/title/tt0072684/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/barry_lyndon",
            poster: "https://m.media-amazon.com/images/M/MV5BNmY0MWY2NDctZDdmMi00MjA1LTk0ZTQtZDMyZTQ1NTNlYzVjXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie55",
        name: "Schumacher",
        releaseYear: "2021",
        runtime: "1h 52m",
        summary:"Through exclusive interviews and archival footage, this documentary traces an intimate portrait of seven-time Formula 1 champion Michael Schumacher.",
        director: ["Hanns-Bruno Kammertöns", "Vanessa Nöcker", "Michael Wech"],
        writers:["Hanns-Bruno Kammertöns", "Vanessa Nöcker", "Michael Wech"],
        actors: ["Ross Brawn", "Flavio Briatore", "Luca Cordero di Montezemolo", "David Coulthard", "Bernie Ecclestone", "Damon Hill", "Mika Häkkinen", "Sebastian Vettel", "Mark Webber" ],
        genre: ["Documentary", "Biography", "Sport"],
        links: {
            imdb: "https://www.imdb.com/title/tt10322274/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/schumacher",
            poster: "https://m.media-amazon.com/images/M/MV5BOWUzYzBjNjAtN2RlNC00YWE5LThlMDEtMjhlOTQwYTY4NTlmXkEyXkFqcGdeQXVyMTI5Nzk4NDQ4._V1_FMjpg_UX1000_.jpg"
        },
    },
    {
        id: "movie56",
        name: "Eyes Wide Shut",
        releaseYear: "1999",
        runtime: "2h 39m",
        summary: "",
        director: ["Stanley Kubrick"],
        actors: ["Tom Cruise", "Nicole Kidman", "Todd Field", "Sydney Pollack", "madison Eginton", "Jackie Sawiris"],
        writers: ["Stanley Kubrick", "Frederic Raphael", "Arthur Schnitzler"],
        genre: ["Drama", "Mystery", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt0120663/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/eyes_wide_shut",
            poster: "https://flxt.tmsimg.com/assets/p23544_p_v13_av.jpg",
        }
    },
    {
        id: "movie57",
        name: "Porco Rosso",
        releaseYear: "1992",
        runtime: "1h 34m",
        summary: "",
        director: ["Hayao Miyazaki"],
        actors: ["Shûichirô Moriyama", "Tokiko Katô", "Bunshi Katsura Vi", "Tsunehiko Kamijô", "Akemi Okamura", "Akio Ôtsuka"],
        writers: ["Hayao Miyazaki"],
        genre: ["Animation", "Adventure", "Comedy"],
        links: {
            imdb: "https://www.imdb.com/title/tt0104652/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/porco_rosso",
            poster: "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/4463b1a9af706a0f148357eb00f77aceec3447ebf543c7b48508145052200394._RI_V_TTW_.jpg",
        }
    },
    {
        id: "movie58",
        name: "Princess Mononoke",
        releaseYear: "1997",
        runtime: "2h 14m",
        summary: "ADD THIS LATER",
        director: ["Hayao Miyazaki"],
        actors: ["Yôji Matsuda", "Yuriko Ishida", "Yûko Tanaka", "Billy Crudup", "Billy Bob Thornton", "Minnie Driver", "John DiMaggio", "Claire Danes"],
        writers: ["Hayao Miyazaki"],
        genre: ["Animation", "Action", "Adventure"],
        links: {
            imdb: "https://www.imdb.com/title/tt0119698/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/princess_mononoke_1999",
            poster: "https://images-na.ssl-images-amazon.com/images/I/81jSJRqb9IL.jpg",
        }
    },
    {
        id: "movie59",
        name: "DUNE",
        releaseYear: "2021",
        runtime: "2h 35m",
        summary: "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
        director: ["Denis Villeneuve"],
        actors: ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya", "Oscar Isaac", "Jason Momoa", "Stellan Skarsgård", "Stephan McKinley Henderson", "Josh Brolin", "javier Bardem", "Sharon Duncan-Brewster", "Chang Chen", "Dave Bautista"],
        writers: ["Jon Spaihts", "Denis Villeneuve", "Eric Roth"],
        genre: ["Action", "Adventure", "Drama"],
        links: {
            imdb: "https://www.imdb.com/title/tt1160419/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/dune_2021",
            poster: "https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F61116cea2313e8bae55a536a%2F-Dune-%2F0x0.jpg%3Ffit%3Dscale",
        }
    },
    {
        id: "movie60",
        name: "No Time to Die",
        releaseYear: "2021",
        runtime: "2h 43m",
        summary: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology",
        director: ["Cory Joji Fukunaga"],
        actors: ["Daniel Craig", "Ana de Armas", "Rami Malek", "Léa Seydoux", "Lashana Lynch", "Ralph Finnes", "Ben Whishaw", "Naomie Harris"],
        writers: ["Neal Purvis", "Robert Wade", "Cary Joji Fukunaga"],
        genre: ["Action", "Adventure", "Thriller"],
        links: {
            imdb: "https://www.imdb.com/title/tt2382320/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/no_time_to_die_2021",
            poster: "https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg",
        }
    },
    {
        id: "movie61",
        name: "Shang-Chi and the Legend of the Ten Rings",
        releaseYear: "2021",
        runtime: "2h 12m",
        summary: "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
        director: ["Destin Daniel Cretton"],
        actors: ["Simu Liu", "Awkwafina", "Tony Chiu-Wai Leung", "Ben Kingsley", "Meng'er Zhang", "Fala Chen", "Michelle Yeoh", "Wah Yuen"],
        writers: ["Dave Callaham", "Destin Daniel Cretton", "Andrew Lanham"],
        genre: ["Action", "Adventure", "Fantasy", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt9376612/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/shang_chi_and_the_legend_of_the_ten_rings",
            poster: "https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
        }
    },
    {
        id: "movie62",
        name: "Wind River",
        releaseYear: "2017",
        runtime: "1h 47m",
        summary: "A veteran hunter helps an FBI agent investigate the murder of a young woman on a Wyoming Native American reservation.",
        director: ["Taylor Sheridan"],
        actors: ["Elizabeth Olsen", "Jeremy Renner", "Graham Greene", "Kelsey Asbille", "Julia Jones", "Teo Briones", "Apesanahkwat", "tantoo Cardinal"],
        writers: ["Taylor Sheridan"],
        genre: ["Crime", "Drama", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt5362988/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/wind_river_2017",
            poster: "https://m.media-amazon.com/images/M/MV5BMTUyMjU1OTUwM15BMl5BanBnXkFtZTgwMDg1NDQ2MjI@._V1_FMjpg_UX1000_.jpg",
        }
    },
    {
        id: "movie63",
        name: "Inglourious Basterds",
        releaseYear: "2009",
        runtime: "2h 33m",
        summary: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        director: ["Quentin Tarantino"],
        actors: ["Brad Pitt", "Diane Kruger", "Eli Roth", "Mélanie Laurent", "Christoph Waltz", "Michael Fassbender", "Daniel Brühl", "Til Schweiger"],
        writers: ["Quentin Tarantino"],
        genre: ["Adventure", "Drama", "War"],
        links: {
            imdb: "https://www.imdb.com/title/tt0361748/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/inglourious_basterds",
            poster: "https://m.media-amazon.com/images/I/81+4I8lZZeL._SL1500_.jpg",
        }
    },
    {
        id: "movie64",
        name: "First Cow",
        releaseYear: "2019",
        runtime: "2h 2m",
        summary: "A skilled cook has traveled west and joined a group of fur trappers in Oregon, though he only finds true connection with a Chinese immigrant also seeking his fortune. Soon the two collaborate on a successful business.",
        director: ["Kelly Reichardt"],
        actors: ["John Magaro", "Orion Lee", "Dylan Smith", "Ewen Bremner", "Rene Auberjonois"],
        writers: ["jonathan Raymond", "Kelly Reichardt"],
        genre: ["Drama", "Western"],
        links: {
            imdb: "https://www.imdb.com/title/tt9231040/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/first_cow",
            poster: "https://m.media-amazon.com/images/M/MV5BMGUzMGEzM2UtMDg2Ny00Yjk1LTgxMTctMWI1ZGM0ZDBiYjgxXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
        }
    },
    {
        id: "movie65",
        name: "Last Night in Soho",
        releaseYear: "2021",
        runtime: "1h 56m",
        summary: "An aspiring fashion designer is mysteriously able to enter the 1960s where she encounters a dazzling wannabe singer. But the glamour is not all it appears to be and the dreams of the past start to crack and splinter into something darker.",
        director: ["Edgar Wright"],
        actors: ["Thomasin McKenzie", "Anya Taylor-Joy", "Matt Smith", "Diana Rigg", "Aimee Cassettari", "Micael Ajao"],
        writers: ["Edgar Wright", "Krysty Wilson-Cairns"],
        genre: ["Drama", "Horror", "Mystery"],
        links: {
            imdb: "https://www.imdb.com/title/tt9639470/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/last_night_in_soho",
            poster: "https://m.media-amazon.com/images/M/MV5BZjgwZDIwY2MtNGZlNy00NGRlLWFmNTgtOTBkZThjMDUwMGJhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        }
    },
    {
        id: "movie66",
        name: "Venom: Let There Be Carnage",
        releaseYear: "2021",
        runtime: "1h 37m",
        summary: "Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution.",
        director: ["Andy Serkis"],
        actors: ["Tom Hardy", "Woody Harrelson", "Michelle Williams", "Naomie Harris", "Reid Scott", "Stephen Graham"],
        writers: ["Kelly Marcel", "Tom Hardy"],
        genre: ["Action", "Adventure", "Sci-Fi", "Comic Book"],
        links: {
            imdb: "https://www.imdb.com/title/tt7097896/",
            rottenTomatoes: "https://www.rottentomatoes.com/m/venom_let_there_be_carnage",
            poster: "https://www.cuopm.com/wp-content/uploads/2021/10/1-1.jpeg",
        }
    },
    // {
    //     id: "movie1",
    //     name: "Rising Arizona",
    //     releaseYear: "",
    //     runtime: "",
    //     summary: "",
    //     director: "",
    //     actors: "",
    //     writers: "",
    //     genre: "",
    //     links: {
    //         imdb: "",
    //         rottenTomatoes: "",
    //         poster: "",
    //     }
    // },
    
];
